### ISSUE TITLE
Image for Library section 

### ISSUE THREAD

**Issue by bellavelo** [creativecommons/cc-cert-lib#1]
Replace the top image 
https://certificates.creativecommons.org/lib/contents/ - Information Stadtbibliothek Gelsenkirchen by Fachstelle für Öffentliche Bibliotheken NRW is licensed CC BY

with 

Graca's Dream by Melissa Fagan, Karlien de Villiers, Marike le Roux is licensed CC BY 
http://bookdash.github.io/bookdash-books/gracas-dream/en/images/05.jpg

http://bookdash.github.io/bookdash-books/gracas-dream/en/

**Comment by cogdog** [comment]
Great image! 

Now in GitHub version https://github.com/creativecommons/cc-cert-lib/blob/master/contents/index.md

And wordpress (added the other pic as a local featured image)
https://certificates.creativecommons.org/lib/contents/
